vieille_sardine_commande_homepage:
    pattern:  /
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:index }

#clients_list:
#    pattern: /clients
#    defaults: { _controller: VieilleSardineUserBundle:User:getUsers }

ajout_produit_commande_vpc:
    pattern:  /CommandeBundle/ajoutProduit
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:CreerFormVPC }
    
id_client_commande_vpc:
    pattern:  /CommandeBundle/identifierClient
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:CreerFormIDClient }
    
recap_commande_vpc:
    pattern:  /CommandeBundle/RecapitulatifCommande
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:CreerFormRecapClient }

ahs_commun_json_IdProduit:
    pattern: /json/IdProduit
    defaults: { _controller: "AhsCommunBundle:Json:IdProduit"}
    
    
InfoProduit:
    pattern: /js/InfoProduit
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:InfoProduitAction}
    
commande_groupee:
    pattern: /CommandeBundle/commandeGroupe
    defaults: { _controller: VieilleSardineCommandeBundle:CommandeGroupe:index  }
    
suivi_Commande_Perso:
    pattern: /suiviCommandePerso
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:suiviCommandePerso}
    
detail_commande:
    pattern: /suiviCommandePerso/{idCmd}
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:detailCommande }


suivi_commande:
    pattern: /CommandeBundle/suiviCommande
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:RecapAllCommandesNomClient }
 