vieille_sardine_commande_homepage:
    pattern:  /
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:index }

#clients_list:
#    pattern: /clients
#    defaults: { _controller: VieilleSardineUserBundle:User:getUsers }

ajout_produit_commande_vpc:
    pattern:  /ajoutProduit
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:CreerFormVPC }

commande_groupee:
    pattern: /commandeGroupe
    defaults: { _controller: VieilleSardineCommandeBundle:CommandeGroupe:index  }
    
detail_commande:
    pattern: /detailCommande
    defaults: { _controller: VieilleSardineCommandeBundle:Detail:detailler }

suivi_commande:
    pattern: /suiviCommande
    defaults: { _controller: VieilleSardineCommandeBundle:SuiviCommande:detailler }
    
id_client_commande_vpc:
    pattern:  /identifierClient
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:CreerFormIDClient }
    
ahs_commun_json_IdProduit:
    pattern: /json/IdProduit
    defaults: { _controller: "AhsCommunBundle:Json:IdProduit"}
    
    
InfoProduit:
    pattern: /js/InfoProduit
    defaults: { _controller: VieilleSardineCommandeBundle:Commande:InfoProduitAction}
    